package Model;

import androidx.room.Database;
import androidx.room.RoomDatabase;

/**
 * The main database class for the application defined using the Room persistence library.
 * This class serves as the main access point to the persisted data.
 *
 * It includes the list of entities contained within the database and the database version.
 * Each DAO associated with the database is abstracted through a method that the Room implementation generates.
 */
@Database(entities = {Location.class}, version = 1)
public abstract class AppDatabase extends RoomDatabase{
    /**
     * Provides access to the {@link LocationDAO} for interacting with the {@code Location} table.
     *
     * @return The {@link LocationDAO} implementation generated by Room.
     */
    public abstract LocationDAO locationDAO();
}
